POST http://localhost:8000/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjczODcyMjU1LCJleHAiOjE2NzM4NzU4NTUsIm5iZiI6MTY3Mzg3MjI1NSwianRpIjoiQ0lveTNkbGowejU5UVRBQiIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.1L5aREE1_4ieeMaQRss2t1kc0CNhHhIijQaTnN5crJw
